DROP SCHEMA test1;
CREATE SCHEMA test1;
USE test1;

CREATE TABLE t (i int, j int, v text, primary key(i), key `asdf` (j)) engine = mosql;

INSERT INTO t VALUES (1,201,'AAAAAAAAAA');
INSERT INTO t VALUES (2,202,'DDDDDDDDDD');
INSERT INTO t VALUES (3,203,'FFFFFFFFFF');
INSERT INTO t VALUES (4,204,'IIIIIIIIII');
INSERT INTO t VALUES (5,201,'AAAAAAAAAA');
INSERT INTO t VALUES (22,202,'DDDDDDDDDD');
INSERT INTO t VALUES (21,203,'FFFFFFFFFF');
INSERT INTO t VALUES (20,207,'IIIIIIIIII');
INSERT INTO t VALUES (18,207,'IIIIIIIIII');
INSERT INTO t VALUES (19,205,'IIIIIIIIII');
INSERT INTO t VALUES (30,203,'IIIIIIIIII');
INSERT INTO t VALUES (29,209,'IIIIIIIIII');

SELECT * FROM t WHERE j = 203;

UPDATE t SET j = 10002 WHERE i = 2;

CREATE TABLE a (i int, primary key(i)) engine = mosql;

INSERT INTO a VALUES (3);
INSERT INTO a VALUES (4);
INSERT INTO a VALUES (5);
INSERT INTO a VALUES (6);


