DROP TABLE IF EXISTS  `tpcb`.`ACCOUNTS`;
DROP TABLE IF EXISTS  `tpcb`.`BRANCHES`;
DROP TABLE IF EXISTS  `tpcb`.`HISTORY`;
DROP TABLE IF EXISTS  `tpcb`.`TELLERS`;

CREATE TABLE  `tpcb`.`ACCOUNTS` (
  `AID` int(11) NOT NULL,
  `BID` int(11) NOT NULL,
  `ABALANCE` decimal(10,0) NOT NULL,
  `FILL` char(60) NOT NULL,
  PRIMARY KEY (`AID`)
) ENGINE=TAPIOCA DEFAULT CHARSET=latin1;

CREATE TABLE  `tpcb`.`BRANCHES` (
  `BID` int(11) NOT NULL,
  `BBALANCE` decimal(10,0) NOT NULL,
  `FILL` char(64) NOT NULL,
  PRIMARY KEY (`BID`)
) ENGINE=TAPIOCA DEFAULT CHARSET=latin1;

CREATE TABLE  `tpcb`.`HISTORY` (
  `BID` int(11) NOT NULL,
  `TID` int(11) NOT NULL,
  `AID` int(11) NOT NULL,
  `DELTA` decimal(10,0) NOT NULL,
  `TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `FILL` char(1) NOT NULL,
  KEY `HISTORY_ACC` (`AID`)
) ENGINE=TAPIOCA DEFAULT CHARSET=latin1;

CREATE TABLE  `tpcb`.`TELLERS` (
  `TID` int(11) NOT NULL,
  `BID` int(11) NOT NULL,
  `TBALANCE` decimal(10,0) NOT NULL,
  `FILL` char(60) NOT NULL,
  PRIMARY KEY (`TID`)
) ENGINE=TAPIOCA DEFAULT CHARSET=latin1;
